# variables common to all Cere nodes
local: { scripts: "~/myscripts", rpc: 9933, wss: 9944 }  # socket for devnet, qanet
public: { rpc: 9934, wss: 9945 } # socket for mainnet, testnet
cere:
  domain: "cere.network"
  dockerhub:
    repo: "cerebellumnetwork/pos-node"
  container:
    name: "cere"
  chain:
    data: "~/cere/chain-data"
  repo:
    install_scripts: "https://github.com/Cerebellum-Network/nodes-installation-scripts.git"
    branch: "master"
  home: "~/cere"
  configs: "~/cere/configs"  # contains all .env files
  scripts: "~/cere/scripts"
  loglevel: debug
