---
- name: operations localhost
  hosts: localhost
  gather_facts: True
  vars_files:
    - vault/secrets.yml      # my encrypted variables

  roles:
    - role: update_hosts_file
      vars:
        group_to_add: cere  # all hosts from cere will be added to /etc/hosts
        ansible_become_password: "{{ local_password }}"

    # create when ssh port changed to 99
    #- role: ssh_include_file

- name: bootstrap validators
  hosts: testing
  gather_facts: True
  vars:
    ansible_user: root
    ansible_port: 22
  pre_tasks:
    - setup:
        gather_subset:
          - os_family
  vars_files:
    - vault/secrets.yml      # my encrypted variables
    - group_vars/all.yml     # variables that apply to all servers
    - group_vars/cere.yml    # variables that apply to all cere servers

  roles:
    - role: bootstrap
    - role: user_profiles
      tags: user_profiles
    - role: ssh_server
      tags: ssh_server

    # - role: bootstrap

    # add local ssh config to ~/.ssh/config.d/<yourservername>
    #- role: ssh_configd_add_node
    #      vars:
    #        server_ip: 
    #
    #    - role: docker_setup
    #      when: ansible_facts['distribution'] == 'Ubuntu'
    #      tags: docker
    #
    #    - role: cere
    #      vars:  # vars here override those defined in role/defaults/main.yml
    #        network: "devnet"  # devnet|devs-cluster-[12345]|mainnet|qanet|testnet
    #
    #    - role: ufw
    #      vars:
    #        ports: { allow: [30333], deny: [9933, 9944] }
    #      tags: ufw
