---
- name: pre-bootstrap operations on localhost
  hosts: localhost
  gather_facts: True
  vars_files:
    - vault/secrets.yml      # my encrypted variables

  roles:
    - role: update_hosts_file
      vars:
        group_to_add: cere  # all hosts from cere will be added to /etc/hosts
        ansible_become_password: "{{ local_password }}"

    # create when ssh port changed to 99
    #- role: ssh_include_file

- name: bootstrap validators
  hosts: testing
  # serial: 5
  gather_facts: True
  vars_files:
    - vault/secrets.yml      # my encrypted variables
    - group_vars/all.yml     # variables that apply to all servers
    - group_vars/cere.yml    # variables that apply to all cere servers

  roles:
    - { role: user_profiles, ansible_user: "root", ansible_port: 22, tags: user_profiles }
    - { role: ssh_server, ansible_user: "root", ansible_port: 22, tags: ssh_server }

    - role: docker_setup
      tags: docker_setup

      # network: devnet|devs-cluster-[12345]|mainnet|qanet|testnet
    - { role: validator_prep, network: "devnet", tags: validator_prep }
      # ntype: validator | full | archive
    - { role: validator_launch, network: "devnet", ntype: "validator", tags: validator_launch }

    - { role: ufw, ports: { allow: [30333], deny: [9933, 9944] }, tags: ufw }

    #- { role: validator_cleanup, network: "devnet", ntype: "validator", tags: validator_cleanup }


- name: post-bootstrap operations on localhost
  hosts: localhost
  vars_files:
    - vault/secrets.yml      # my encrypted variables
    - group_vars/all.yml     # variables that apply to all servers
    - group_vars/cere.yml    # variables that apply to all cere servers

  roles:
      # adds hosts to ~/.ssh/config.d/<inventory-group>
    - role: ssh_include_file
      tags: ssh_include_file

