---
- name: get validator info
  hosts: cere
  gather_facts: True
  vars_files:
    - vault/secrets.yml      # my encrypted variables
    - group_vars/all.yml     # variables that apply to all servers
    - group_vars/cere.yml    # variables that apply to all cere servers

  roles:
    - role: server_info
