    - name: store info in text file on ansible controller
      local_action:
        module: ansible.builtin.lineinfile
        dest: "{{ local.outputs }}/{{ ansible_hostname }}-details-{{ ansible_date_time.time }}.txt"
        line: "{{ item }}"
        create: yes
        insertafter: EOF
      loop:
        - "{{ ansible_facts.default_ipv4.address }}"
        - "{{ ansible_memtotal_mb }}"
        - "{{ hdinfo.stdout }}"
        - "{{ ansible_processor[2] }}"
        - "{{ ansible_processor_cores }}"
        - "{{ ansible_processor_count }}"
        - "{{ ansible_processor_nproc }}"
        - "{{ ansible_processor_threads_per_core }}"
        - "{{ ansible_processor_vcpus }}"
      when: not ansible_check_mode
