---
# tasks file for roles/ssh_server
- include_vars: vault/secrets.yml

- name: "ensure openssh-server"
  ansible.builtin.apt:
    name: "openssh-server"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- ansible.builtin.stat:
    path: "/home/{{ admin }}/.ssh"
  register: ssh_folder

- name: "ensure ~/.ssh dir for {{ item.name }}"
  file:
    path: "/home/{{ item.name }}/.ssh/"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  become: true
  loop: "{{ admins }}"
  register: local_ssh_folder_created
  when: not ssh_folder.stat.exists

  # below template uses ssh.public var from vault/secrets.yml
  # better to have it encrypted
- name: "template authorized keys file to server for admin"
  template:
    src: authorized_keys.j2
    dest: '/home/{{ admin }}/.ssh/authorized_keys'
    force: yes
    mode: '0600'
    owner: "{{ admin }}"
    group: "{{ admin }}"
  become_user: "{{ admin }}"
  become: true
  when: (ssh_folder.stat.exists or local_ssh_folder_created is succeeded)


- name: change ssh port in file
  block:
    - name: /etc/services
      lineinfile:
        path: /etc/services
        # the string to search
        regexp: "SSH Remote Login Protocol"
        # to be replaced by
        line: "ssh\t\t{{ ssh.port }}/tcp\t\t\t\t# SSH Remote Login Protocol"
        state: present
        backup: true

    - name: /etc/ufw/applications.d/openssh-server
      lineinfile:
        path: /etc/ufw/applications.d/openssh-server
        # the string to search
        regexp: "ports=22/tcp"
        # to be replaced by
        line: "ports={{ ssh.port }}/tcp"
        state: present
        backup: true
        validate: ufw app update %s
        # sed -e '/22\/tcp/s/22/secretnumberhere/'
  become: true

- name: validate sshd configuration and template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify:
    - restart sshd
  become: true

- name: disable root user
  command: passwd -l root
  become: true

